POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2MWZiMWI2MzdlMDcyNTRhMWNjYzI1NzIiLCJpYXQiOjE2NDQxMDU4ODB9.kBFgTCHJAleDkISm-mPKXiKpClW2ANRdGevuALvI7Ls

{
    "title": "The end is near",
    "author": "Believers",
    "url": "http://martin-fowler.com/articles/microservices"
}
